[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run migrate && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
releaseCommand = "npx prisma generate"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3